### PR TITLE
Improved Browserify compatibility

### PR DESCRIPTION
**Pull request by mchambaud**
* Package.json should not specify minified version as main.
* Module should export itself for UMD builds.

### CODE REVIEW

**Comment by oblador** [comment]
Looks great, thanks!

**Comment by mchambaud** [comment]
Any chance we see a new build soon? We're shipping soon!

**Comment by mchambaud** [comment]
Awesome thank you!

**Comment by ctaepper** [comment]
to make that even more compliant with best practices, module.exports should not export the module itsself, but the name of the module, i.e. `module.exports = "duScroll"` or `module.exports = duScroll.name`

**Comment by mchambaud** [comment]
I agree with @ctaepper that's how I do it for myself, but I find people tend to export the module itself.

@oblador do you have a preference?

**Comment by ctaepper** [comment]
those people just don't know better yet... :)

**Comment by oblador** [comment]
Using angular with browserify makes me a bit uncomfortable because they both try to solve the same problem. Haven't read any best practices for this and am not too opinionated, personally for my angular projects I export both :-) Somehow feels weird for an AMD to only return strings.

Got any links on the matter?

**Comment by ctaepper** [comment]
> Finally, to match the convention for CommonJS set up within Angular, you’ll need to expose the string that people use to load your module. You’ll do this using module.exports. Note, this is a convention that Angular uses, and it doesn’t necessarily apply to other front-end projects.

see http://blog.npmjs.org/post/114584444410/using-angulars-new-improved-browserify-support

**Comment by oblador** [comment]
@ctaepper: As of 0.7.4 this is now the behavior. If you want to access the module itself then do a `require('angular-scroll/angular-scroll')`.

**Comment by ctaepper** [comment]
:+1:

**Comment by mchambaud** [comment]
:+1:

**Comment by oblador** [comment]
It's actually 1.0.0 now since it broke someone's installation :-)

**Pull request merged**
